# Generated by Django 5.0.6 on 2024-05-14 10:34

import redbox_app.redbox_core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redbox_core", "0005_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="expiry_date",
            field=models.DateField(
                default=redbox_app.redbox_core.models.get_default_expiry_date
            ),
        ),
    ]
